windowrule {
  name = Nautilus
  match:class = org.gnome.Nautilus

  size = 1200 600
  float = true
  pin = true
}
windowrule {
  name = GnomeDisk
  match:class = gnome-disks

  size = 700 400
  float = true
  #pin = true
}
