quit-after-last-window-closed = true
shell-integration = zsh
shell-integration-features = cursor,sudo,title,no-ssh-env,no-ssh-terminfo,path
title-report = true
quick-terminal-position = top
quick-terminal-animation-duration = 0.5
quick-terminal-keyboard-interactivity = exclusive
clipboard-read = allow
clipboard-paste-protection = false
window-show-tab-bar = never
window-theme = ghostty
window-decoration = none
window-padding-x = 0
window-padding-y = 0
background-opacity = 0.75
background-blur = true
unfocused-split-opacity = 0.85
selection-clear-on-copy = true

font-size = 20
font-family = "JetBrainsMono Nerd Font"
font-feature = ["liga", "calt"]
mouse-shift-capture = true
right-click-action = copy-or-paste
focus-follows-mouse = true
keybind = ctrl+shift+r=reload_config

keybind = ctrl+shift+p=close_surface
keybind = ctrl+shift+q=new_tab

keybind = ctrl+shift+l=goto_split:previous
keybind = ctrl+shift+k=goto_split:next
keybind = ctrl+shift+o=toggle_tab_overview


keybind = ctrl+shift+g=toggle_split_zoom
keybind = ctrl+shift+f=toggle_quick_terminal
keybind = ctrl+shift+z=undo

keybind = ctrl+shift+m=previous_tab
keybind = ctrl+shift+n=next_tab

keybind = ctrl+shift+w=resize_split:up,20
keybind = ctrl+shift+d=resize_split:down,20
keybind = ctrl+shift+s=resize_split:left,20
keybind = ctrl+shift+a=resize_split:right,20

keybind = ctrl+shift+u=new_split:down
keybind = ctrl+shift+j=new_split:left
keybind = ctrl+shift+y=new_split:up
keybind = ctrl+shift+h=new_split:right

config-file = ./Everforest.toml
