animations {
	animation = windowsIn, 1, 9, oiExpo
	animation = windowsOut, 1, 9, ioExpo
	animation = windowsMove, 1, 9, ioBack

	animation = layersIn, 1, 10, oiBack
	animation = layersOut, 1, 10, oiCirc

	animation = workspacesIn, 1, 5, ioSine
	animation = workspacesOut, 1, 5, oiSine

	animation = specialWorkspaceOut, 1, 25, ioExpo, slidevert
	animation = specialWorkspaceIn, 1, 10, oiQuint, slidevert

	animation = fadeIn, 1, 10, oiQuart
	#animation = fadeOut, 1, 10, ioQuart
	#animation = fadeSwitch, 1, 100, oiBack
	#animation = fadePopupsIn, 1, 3, oiQuint
	animation =  zoomFactor, 1, 7, oiExpo
}
