animations {
	bezier = iSine, 0.12, 0, 0.39, 0
	bezier = oSine, 0.61, 1, 0.88, 1
	bezier = ioSine, 0.37, 0, 0.63, 1
	bezier = oiSine, 0.63, 1, 0.37, 0

	bezier = iQuad, 0.11, 0, 0.5, 0
	bezier = oQuad, 0.5, 1, 0.89, 1
	bezier = ioQuad, 0.45, 0, 0.55, 1
	bezier = oiQuad, 0.55, 1, 0.45, 0

	bezier = iCubic, 0.32, 0, 0.67, 0
	bezier = oCubic, 0.33, 1, 0.68, 1
	bezier = ioCubic, 0.65, 0, 0.35, 1
	bezier = oiCubic, 0.35, 1, 0.65, 0

	bezier = iQuart, 0.5, 0, 0.75, 0
	bezier = oQuart, 0.25, 1, 0.5, 1
	bezier = ioQuart, 0.76, 0, 0.24, 1
	bezier = oiQuart, 0.24, 1, 0.76, 0

	bezier = iQuint, 0.64, 0, 0.78, 0
	bezier = oQuint, 0.22, 1, 0.36, 1
	bezier = ioQuint, 0.83, 0, 0.17, 1
	bezier = oiQuint, 0.17, 1, 0.83, 0

	bezier = iExpo, 0.7, 0, 0.84, 0
	bezier = oExpo, 0.16, 1, 0.3, 1
	bezier = ioExpo, 0.87, 0, 0.13, 1
	bezier = oiExpo, 0.13, 1, 0.87, 0

	bezier = iCirc, 0.55, 0, 1, 0.45
	bezier = oCirc, 0, 0.55, 0.45, 1
	bezier = ioCirc, 0.85, 0, 0.15, 1
	bezier = oiCirc, 0.15, 1, 0.85, 0

	bezier = iBack, 0.36, 0, 0.66, -0.56
	bezier = oBack, 0.34, 1.56, 0.64, 1
	bezier = ioBack, 0.68, -0.6, 0.32, 1.6
	bezier = oiBack, 0.32, 1.6, 0.68, -0.6
}
