general {
	hide_cursor = true
}
animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
}

background {
    path = ~/Pictures/Wallpapers/current_wallpaper
    blur_passes = 2
    blur_size = 9
}

input-field {
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.33
    font_size = 20
    dots_spacing = 0.15
    outer_color = rgb(24, 122, 119)  
    inner_color = rgb(9,24,25)
    font_color = rgb(209, 144, 46)
    fade_on_empty = true
    check_color = rgb(208, 47, 100)
}

label {
    text = <b><i>$TIME</i></b>
    color = rgb(24, 122, 119)
    font_size = 80
    size = 211,111
    position = 0, 80
    halign = center
    valign = center
}
label {
    text = <i>¡¡¡Willkommen <b>$USER</b>!!!</i>
    color = rgb(208, 47, 100)
    font_size = 15
    halign = center
    valign = bottom
    position = 0, 50 
}
