env = HYPRSHOT_DIR,/home/Zukunter/User/Fixed/Pictures
env = XCURSOR_PATH,~/User/ElBastionDelOlvido/Desktop/Sources/Cursors
#env = XCURSOR_THEME,ArcAurora
#env = XCURSOR_SIZE,30

# Set Cursor
exec-once = hyprctl setcursor ArcAurora 30
# Notifications
exec-once = mako -c ~/User/ElBastionDelOlvido/Desktop/Mako.toml
exec-once = swww-daemon
# Keyboard False
exec-once = ydotoold --socket-path=$XDG_RUNTIME_DIR/.ydotool_socket --socket-own=$(id -u):$(id -g)
# Start Waybar
exec-once = waybar -c ~/User/ElBastionDelOlvido/Desktop/Waybar/General.yaml -s ~/User/ElBastionDelOlvido/Desktop/Waybar/General.css
# Change Wallpaper and Timer for it
exec-once = ~/User/ElBastionDelOlvido/Desktop/Sources/Scripts/ChangeWallpaper.sh && ~/User/ElBastionDelOlvido/Desktop/Sources/Scripts/Timer.sh

# Connect Others files

source = ~/User/ElBastionDelOlvido/Desktop/Hyprland/Behave/Input.conf
#It seems to not work
#source = ~/User/ElBastionDelOlvido/Desktop/Hyprland/Behave/Plugins/Expo.conf
source = ~/User/ElBastionDelOlvido/Desktop/Hyprland/Behave/Rules/Fixing.conf
source = ~/User/ElBastionDelOlvido/Desktop/Hyprland/Behave/Rules/FloatingSelecting.conf
source = ~/User/ElBastionDelOlvido/Desktop/Hyprland/Behave/Rules/PictureInPicture.conf
source = ~/User/ElBastionDelOlvido/Desktop/Hyprland/Behave/Rules/Mpv.conf

source = ~/User/ElBastionDelOlvido/Desktop/Hyprland/Views/Animations/Beziers.conf
source = ~/User/ElBastionDelOlvido/Desktop/Hyprland/Views/Animations/Animations.conf
source = ~/User/ElBastionDelOlvido/Desktop/Hyprland/Views/Decorations/General.conf
source = ~/User/ElBastionDelOlvido/Desktop/Hyprland/Views/Decorations/Cursor.conf
source = ~/User/ElBastionDelOlvido/Desktop/Hyprland/Views/Decorations/Decoration.conf


source = ~/User/ElBastionDelOlvido/Desktop/Hyprland/Submaps/Variables.conf
source = ~/User/ElBastionDelOlvido/Desktop/Hyprland/Submaps/Universal.conf
source = ~/User/ElBastionDelOlvido/Desktop/Hyprland/Submaps/Software/Hyprland.conf
source = ~/User/ElBastionDelOlvido/Desktop/Hyprland/Submaps/Characters/Basic.conf
source = ~/User/ElBastionDelOlvido/Desktop/Hyprland/Submaps/Characters/Special.conf
source = ~/User/ElBastionDelOlvido/Desktop/Hyprland/Submaps/Software/Ghostty.conf
source = ~/User/ElBastionDelOlvido/Desktop/Hyprland/Submaps/Software/ScreenPicker.conf
source = ~/User/ElBastionDelOlvido/Desktop/Hyprland/Submaps/Software/Waybar.conf
