bindun = , t, exec, mpv --no-video /home/Zukunter/User/ElBastionDelOlvido/Desktop/Sources/Piano/A.mp3
bindun = , g, exec, mpv --no-video /home/Zukunter/User/ElBastionDelOlvido/Desktop/Sources/Piano/A_1.mp3
bindun = , h, exec, mpv --no-video /home/Zukunter/User/ElBastionDelOlvido/Desktop/Sources/Piano/A_1f.mp3
bindun = , b, exec, mpv --no-video /home/Zukunter/User/ElBastionDelOlvido/Desktop/Sources/Piano/A_1s.mp3
bindun = , n, exec, mpv --no-video /home/Zukunter/User/ElBastionDelOlvido/Desktop/Sources/Piano/A_2.mp3
bindun = , m, exec, mpv --no-video /home/Zukunter/User/ElBastionDelOlvido/Desktop/Sources/Piano/A_2s.mp3
bindun = , o, exec, mpv --no-video /home/Zukunter/User/ElBastionDelOlvido/Desktop/Sources/Piano/Af.mp3
bindun = , l, exec, mpv --no-video /home/Zukunter/User/ElBastionDelOlvido/Desktop/Sources/Piano/As.mp3
bindun = , q, exec, mpv --no-video /home/Zukunter/User/ElBastionDelOlvido/Desktop/Sources/Piano/B.mp3
bindun = , s, exec, mpv --no-video /home/Zukunter/User/ElBastionDelOlvido/Desktop/Sources/Piano/B_1.mp3
bindun = , a, exec, mpv --no-video /home/Zukunter/User/ElBastionDelOlvido/Desktop/Sources/Piano/B_1f.mp3
