bindue = $H, less, exec, wtype -k BackSpace
bindue = $H, bar, exec, wtype -k Return
bindue = , less, exec, wtype "_"
bindue = , bar, exec, wtype "0"

#bindu = , $mul, hyprexpo:expo, toggle
bindue = , $div, togglefloating
bindu = , $sub, killactive

bindue = , $add, workspace, +1
bindue = , $ent, workspace, -1

bindue = , $l, cyclenext, prev
bindue = , $m, cyclenext

bindue = , $h, swapnext, prev
bindue = , $u, swapnext
bindu = , $p, fullscreen
bindu = , $r, togglespecialworkspace

bindu = , $e, exec, pidof waybar && killall waybar || waybar -c ~/User/ElBastionDelOlvido/Desktop/Waybar/General.yaml -s ~/User/ElBastionDelOlvido/Desktop/Waybar/General.css &
bindu = , $d, pin
bindu = , $n, exec, fuzzel --config ~/User/ElBastionDelOlvido/Desktop/Fuzzel.toml

bindu = , $ins, exec, ghostty
bindu = , $del, exec, hyprlock -c ~/User/ElBastionDelOlvido/Desktop/Hyprland/Lock.conf

bindmu = $S, mouse:272, movewindow
bindmu = $S, mouse:273, resizewindow
bindu = $S, Escape, submap, reset

bindu = $S, 0, workspace, 10
bindu = $S, 1, workspace, 1
bindu = $S, 2, workspace, 2
bindu = $S, 3, workspace, 3
bindu = $S, 4, workspace, 4
bindu = $S, 5, workspace, 5
bindu = $S, 6, workspace, 6
bindu = $S, 7, workspace, 7
bindu = $S, 8, workspace, 8
bindu = $S, 9, workspace, 9
#Moving
bindue = $S, X, swapnext
bindue = $S, Z, swapnext, prev
#bindu = $S, E, hyprexpo:expo, toggle
bindue = $S, Tab, cyclenext
bindue = $S, bar, cyclenext, prev
bindue = $S, A, workspace, -1
bindue = $S, D, workspace, +1
#Toggle
bindu = $S, R, exec, pidof waybar && killall waybar || waybar -c ~/User/ElBastionDelOlvido/Desktop/Waybar/General.yaml -s ~/User/ElBastionDelOlvido/Desktop/Waybar/General.css &
bindu = $S, P, pin
bindu = $S, S, togglespecialworkspace
bindu = $S, F, fullscreen
bindu = $S, C, togglefloating
#Extra
bindue = $S, W, killactive
bindue = $S, Q, exec, ghostty
bindu = $S, N, exec, hyprlock -c ~/User/ElBastionDelOlvido/Desktop/Hyprland/Lock.conf
bindu = $S, M, exec, fuzzel --config ~/User/ElBastionDelOlvido/Desktop/Fuzzel.toml
 
bindu = $C, $apos, exec, ~/User/ElBastionDelOlvido/Desktop/Sources/Scripts/SelectWallpaper.sh
bindu = $C, $ques, exec, ~/User/ElBastionDelOlvido/Desktop/Sources/Scripts/ChangeWallpaper.sh

#Submaps
bindu = , $dead, exec, notify-send -a "System" "$ Basic Char @"
bindu = , $dead, submap, $ Basic Char @

bindu = $S, $dead, exec, notify-send -a "System" "::Special Char^^"
bindu = $S, $dead, submap, ::Special Char^^

bindu = , $brcl, exec, notify-send -a "System" " Hyprland "
bindu = , $brcl, submap,  Hyprland 
bindu = $S, P, exec, notify-send -a "System" "  Screen Picker  "
bindu = $S, P, submap,  Screen Picker
bindu = $S, ntilde, exec, notify-send -a "System" " Waybar  "
bindu = $S, ntilde, submap,  Waybar 
bindu = , $brcr, exec, notify-send -a "System" "󰊠 Ghostty 󰊠"
bindu = , $brcr, submap, 󰊠 Ghostty 󰊠



bindu = , $ques, exec, wtype -k Escape && wtype -k Escape
bindu = $H, $zero, exec,wtype -k Escape && wtype -k Escape && wtype -k Space && wtype "E" 
bindu = , $plus, exec,  wtype -k Escape && wtype -k Escape && wtype -k Space  && wtype "F"
bindu = , $apos, exec,  wtype -k Escape && wtype -k Escape && wtype -k Space && wtype "v"

bindu = $H, $zero, exec, notify-send -a "System" " Insert : End  "
bindu = , $plus, exec, notify-send -a "System" " Insert : After  "
bindu = , $apos, exec, notify-send -a "System" " Visual : Block  "
bindu = , $ques, exec, notify-send -a "System" " Normal  "

