#Modificaiers
$M = MOD2
$S = SUPER
$H = SHIFT
$A = ALT
$C = CONTROL
#6-team
$in = Insert
$ho = Home
$pr = Prior
$sr = Delete
$ed = End
$nt = Next
#Special
$div = Kp_Divide
$mul = Kp_Multiply
$sub = Kp_Subtract
$add = Kp_Add
$ent = Kp_Enter
$ins = Kp_Insert
$del = Kp_Delete
#9-team
$h = Kp_Home
$p = Kp_Prior
$l = Kp_Left
$r = Kp_Right
$m = Kp_Begin
$u = Kp_Up
$d = Kp_Down
$e = Kp_End
$n = Kp_Next
#Submap
$dead = dead_acute
$plus = plus
$brcl = braceleft
$brcr = braceright
$ques = questiondown
$zero = 0
$apos = apostrophe
