general {
    gaps_in = 5
    gaps_out = 0

    border_size = 0

    col.active_border = rgba(D1902EFF) rgba(D02F64FF) 45deg
    col.inactive_border = rgba(187A77FF)

    resize_on_border = false

    allow_tearing = false

    # layout = dwindle
    layout = master
}
