submap = 󰊠 Ghostty 󰊠

#Fullscreen
bind = , F, exec, ydotool key 29:1 42:1 34:1 34:0 42:0 29:0 #G
#Close Surface
binde = , W, exec, ydotool key 29:1 42:1 25:1 25:0 42:0 29:0 #P
#New Tab
bind = , Q, exec, ydotool key 29:1 42:1 16:1 16:0 42:0 29:0 #Q
#General View
bind = , E, exec, ydotool key 29:1 42:1 24:1 24:0 42:0 29:0 #Mini wiev
#Undo
bind = , U, exec, ydotool key 29:1 42:1 44:1 44:0 42:0 29:0 #Z
#Quick Terminal
bind = , P, exec, ydotool key 29:1 42:1 33:1 33:0 42:0 29:0 #F
#Reload Configuration
bind = , R, exec, ydotool key 29:1 42:1 19:1 19:0 42:0 29:0 #R


#Next Tab
binde = , Tab, exec, ydotool key 29:1 42:1 50:1 50:0 42:0 29:0 #M
#Prev Tab
binde = $H, Tab, exec, ydotool key 29:1 42:1 49:1 49:0 42:0 29:0 #N

#Next Split
binde = , A, exec, ydotool key 29:1 42:1 38:1 38:0 42:0 29:0 #L
#Prev Split
binde = , D, exec, ydotool key 29:1 42:1 37:1 37:0 42:0 29:0 #K

#New Split
binde = , J, exec, ydotool key 29:1 42:1 36:1 36:0 42:0 29:0 #J
binde = , I, exec, ydotool key 29:1 42:1 21:1 21:0 42:0 29:0 #Y
binde = , L, exec, ydotool key 29:1 42:1 35:1 35:0 42:0 29:0 #H
binde = , K, exec, ydotool key 29:1 42:1 22:1 22:0 42:0 29:0 #U


bind = , Space, submap, reset
