submap =  Hyprland 

bind = $A, W, movetoworkspacesilent, special
bind = , W, movetoworkspace, special
bind = $A, S, movetoworkspacesilent, -0
bind = , S, movetoworkspace, -0

binde = , A, movetoworkspace, -1
binde = , D, movetoworkspace, +1
binde = $A, A, movetoworkspacesilent, -1
binde = $A, D, movetoworkspacesilent, +1

#Move Between Workspaces
bind = , 0, movetoworkspace, 10
bind = , 1, movetoworkspace, 1
bind = , 2, movetoworkspace, 2
bind = , 3, movetoworkspace, 3
bind = , 4, movetoworkspace, 4
bind = , 5, movetoworkspace, 5
bind = , 6, movetoworkspace, 6
bind = , 7, movetoworkspace, 7
bind = , 8, movetoworkspace, 8
bind = , 9, movetoworkspace, 9
bind = $A, 0, movetoworkspacesilent, 10
bind = $A, 1, movetoworkspacesilent, 1
bind = $A, 2, movetoworkspacesilent, 2
bind = $A, 3, movetoworkspacesilent, 3
bind = $A, 4, movetoworkspacesilent, 4
bind = $A, 5, movetoworkspacesilent, 5
bind = $A, 6, movetoworkspacesilent, 6
bind = $A, 7, movetoworkspacesilent, 7
bind = $A, 8, movetoworkspacesilent, 8
bind = $A, 9, movetoworkspacesilent, 9

#Windows
bindm = , mouse:272, movewindow
bindm = , mouse:273, resizewindow
#Zoom
binde = , O, exec, hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float - 0.25')
binde = , P, exec, hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float + 0.25')
bind = , I, exec, hyprctl keyword cursor:zoom_factor 1.0
#Temperature
binde = , Q, exec, ~/User/ElBastionDelOlvido/Desktop/Sources/Scripts/Sunset.sh down
binde = , E, exec, ~/User/ElBastionDelOlvido/Desktop/Sources/Scripts/Sunset.sh up
binde = , R, exec, ~/User/ElBastionDelOlvido/Desktop/Sources/Scripts/Sunset.sh reset
#Submaps
bind = , L, exec, notify-send -a "Submap" "   Screen Picker  "
bind = , L, submap,  Screen Picker

bind = , ntilde, exec, notify-send -a "Submap" " Waybar  "
bind = , ntilde, submap,  Waybar 

bindn =  , Space, submap, reset
