submap =  Hyprland 

bind = $AG, W, movetoworkspacesilent, special
bind = , W, movetoworkspace, special
bind = $AG, S, movetoworkspacesilent, -0
bind = , S, movetoworkspace, -0

binde = , A, movetoworkspace, -1
binde = , D, movetoworkspace, +1
binde = $AG, A, movetoworkspacesilent, -1
binde = $AG, D, movetoworkspacesilent, +1

#Move Between Workspaces
bindu = $H, 0, workspace, 10
bindu = $H, 1, workspace, 1
bindu = $H, 2, workspace, 2
bindu = $H, 3, workspace, 3
bindu = $H, 4, workspace, 4
bindu = $H, 5, workspace, 5
bindu = $H, 6, workspace, 6
bindu = $H, 7, workspace, 7
bindu = $H, 8, workspace, 8
bindu = $H, 9, workspace, 9
bind = , 0, movetoworkspace, 10
bind = , 1, movetoworkspace, 1
bind = , 2, movetoworkspace, 2
bind = , 3, movetoworkspace, 3
bind = , 4, movetoworkspace, 4
bind = , 5, movetoworkspace, 5
bind = , 6, movetoworkspace, 6
bind = , 7, movetoworkspace, 7
bind = , 8, movetoworkspace, 8
bind = , 9, movetoworkspace, 9
bind = $AG, 0, movetoworkspacesilent, 10
bind = $AG, 1, movetoworkspacesilent, 1
bind = $AG, 2, movetoworkspacesilent, 2
bind = $AG, 3, movetoworkspacesilent, 3
bind = $AG, 4, movetoworkspacesilent, 4
bind = $AG, 5, movetoworkspacesilent, 5
bind = $AG, 6, movetoworkspacesilent, 6
bind = $AG, 7, movetoworkspacesilent, 7
bind = $AG, 8, movetoworkspacesilent, 8
bind = $AG, 9, movetoworkspacesilent, 9

#Windows
bindm = , mouse:272, movewindow
bindm = , mouse:273, resizewindow
#Zoom
binde = , O, exec, hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float - 0.25')
binde = , P, exec, hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float + 0.25')
bind = , I, exec, hyprctl keyword cursor:zoom_factor 1.0
#Temperature
binde = , Q, exec, ~/User/ElBastionDelOlvido/Desktop/Sources/Scripts/Sunset.sh down
binde = , E, exec, ~/User/ElBastionDelOlvido/Desktop/Sources/Scripts/Sunset.sh up
binde = , R, exec, ~/User/ElBastionDelOlvido/Desktop/Sources/Scripts/Sunset.sh reset
#Submaps
bind = , L, exec, notify-send -a "Submap" "   Screen Picker  "
bind = , L, submap,  Screen Picker

bind = , ntilde, exec, notify-send -a "Submap" " Waybar  "
bind = , ntilde, submap,  Waybar 

bindn =  , Space, submap, reset
