submap =  Screen Picker, reset

bind = , S, exec, hyprpicker -a -f hex
bind = , A, exec, hyprpicker -a -f hsl
bind = , D, exec, hyprpicker -a -f rgb
bind = , W, exec, hyprpicker -a -f hsv
bind = , E, exec, hyprpicker -a -f cmyk
bind = , Q, exec, hyprpicker

bind = , ntilde, exec, hyprshot -m window
bind = , O, exec, hyprshot -m active
bind = , L, exec, hyprshot -m region
bind = , P, exec, hyprshot -m output

bind = $A, ntilde, exec, hyprshot -m window -z
bind = $A, O, exec, hyprshot -m active -z
bind = $A, L, exec, hyprshot -m region -z
bind = $A, P, exec, hyprshot -m output -z

bind = , Space, submap, reset
