submap =  Waybar 

binde = , D, exec, playerctl next
binde = , P, exec, playerctl play-pause
binde = , A, exec, playerctl previous

binde = , F, exec, hyprctl dispatch exec '[float; pin; size 1000 700; center] nautilus'
binde = , Q, exec, hyprctl dispatch exec '[float; pin; size 900 700; center] ghostty -e lf'
binde = , E, exec, hyprctl dispatch exec '[float; pin; size 700 500; center] ghostty -e zsh'

binde = , W, exec,pamixer -i 1
binde = , S, exec, pamixer -d 1

bind = , catchall, submap, reset
