submap =  Waybar 

binde = , D, exec, playerctl next
binde = , P, exec, playerctl play-pause
binde = , A, exec, playerctl previous

binde = , W, exec,pamixer -i 1
binde = , S, exec, pamixer -d 1

bind = , catchall, submap, reset
