submap = ::Special Char^^, reset

bind = ,q, exec, wtype -- '<='
bind = ,w, exec, wtype -- "&&" 
bind = ,e, exec, wtype ">="
bind = ,r, exec, wtype "?" 
bind = ,y, exec, wtype "%"
bind = ,u, exec, wtype "$"
bind = ,i, exec, wtype "*"
bind = ,o, exec, wtype "]"
bind = ,p, exec, wtype "}"

bind = ,a, exec, wtype ";;"
bind = ,s, exec, wtype "=="
bind = ,d, exec, wtype "::"
bind = ,f, exec, wtype "|"  
bind = ,g, exec, wtype "¬" 
bind = ,h, exec, wtype "@"
bind = ,j, exec, wtype -k numbersign
bind = ,k, exec, wtype "+" 
bind = ,l, exec, wtype ")"
bind = ,ntilde, exec, wtype ">"

bind = ,z, exec, wtype "~" 
bind = ,x, exec, wtype "^" 
bind = ,c, exec, wtype "!="  

bind = ,v, exec, wtype "€" 
bind = ,b, exec, wtype "¡"
bind = ,n, exec, wtype "¿"  

bind = ,m, exec, wtype "”" 
bind = ,comma, exec, wtype -k grave
bind = ,period, exec, wtype '"'  
bind = ,minus, exec, wtype "'"

bind = , catchall, submap, reset
